#!/usr/bin/ruby

require 'net/http'
require 'json'

json_string = Net::HTTP.get(URI('https://map10.freifunk-ulm.de/data/nodes.json'))
json_object = JSON.parse(json_string)

user_stats = {}
json_object['nodes'].each { |node_info| user_stats[node_info['nodeinfo']['hostname']] = node_info['statistics']['clients'] }

open(Time.now.strftime('%Y-%m-%d') + '_ffulm.log', 'a') do |f|
  f.puts ({ :date => Time.now.strftime('%Y-%m-%d %H:%M'), :user_stats => user_stats }.to_json)
end
